### ISSUE TITLE
[Assistance Sought 🙏]

### ISSUE THREAD

**Issue by aretrace** [lukemiller01/docuclimb#1]
Hi Luke 👋,

I see you are using a stack very similar to what I what to use, if it's not too much trouble could you check the following example and see what I'm doing wrong: https://codesandbox.io/p/sandbox/tla-njs-app-dir-k5xpz3?file=%2Fsrc%2Fapp%2Fns.tsx

Thank you for your time.

**Comment by lukemiller01** [comment]
Hi @aretrace, I'm happy to help out! I'll spend a few minutes reviewing your code within the next few days. If you solve your problem before I respond again, please let me know!

**Comment by lukemiller01** [comment]
Hi @aretrace.

Your problem lies in fetching asynchronous data in a React client component. To fetch data in NextJS 13, you must use the useEffect hook in a client component or it must be a React server component.

I see you've tried the new "use" function. I'm not familiar with "use" yet, but [Vercel's beta docs](https://beta.nextjs.org/docs/data-fetching/fetching) specifically state that fetch & use don't work in client components (as of the time of writing this).

In order to fetch data, use a React Server Component which passes the necessary state/functions as props to a client component (if needed). I'm unfamiliar with Valtio, but it seems it must be used in a client component since it uses the useEffect Hook. This may or may not pose another problem in your app.

Does this answer your question?

**Comment by aretrace** [comment]
How would you deal with real-time subscriptions? I'm using the traditional `pages` directory as the pocketbase js sdk behaves differently with the new `app` directory. 

What I'm ultimately trying to achieve is simply:
1. Read row from SQLite
2. Render row data
3. When row data changes, auto-rerender the component to reflect changes

I would like to use the new `app` directory, but really all I'm trying to do is what I mentioned above. There are multiple solutions for this (SQL triggers, WatermelonDB) but pocketbase has some really nice properties and a simple API. Currently, its real-time feature is the closest thing I found to achieving this but I'm having a bit of trouble trying to incorporate react with the real-time feature in Next.js.

**Comment by lukemiller01** [comment]
@aretrace I've never used Pocketbase's Server Sent Events feature. I'd imagine it's completely incompatible with RSCs because the Pocketbase server is different from the NextJS server.

A "hacky" workaround could be to refetch your data in intervals using the "revalidate" parameter in a server component. This was called Incremental Static Regeneration in Next 12. This line refetches data every second:

`fetch('https://...', { next: { revalidate: 1 } });`

If this doesn't solve your problem, try researching how subscriptions in Next 12 are implemented. Next 13 solves the same problems Next 12 does with a more streamlined DX - of course, with some notable exceptions! I've never built an SSE feature in Next, but I'd imagine if you can do it in Next 12, you'll have a good idea of how to do it in Next 13 (if it's possible!).

Good luck!
